name: Bug Report
description: Report a bug or unexpected behavior in the project.
labels: "bug"
body:
  -type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please complete the form below to help understand the issue better.
        Fields marked with a `*` are required.

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: Provide a clear and concise title for the bug.
      placeholder: "Abort run behaviour"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the issue in detail. Include what you were doing when the bug occurred and any other relevant context.
      placeholder: "When I try to abort the run, ..."
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Provide a list of steps to reproduce the issue.
      placeholder: |
        1. Open the VAAC-D interface.
        2. Start a 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen instead.
      placeholder: "The run should ..."
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: Describe what actually happened.
      placeholder: "The following error message was shown..."
    validations:
      required: true

- type: textarea
    id: logs_or_screenshots
    attributes:
      label: Logs or Screenshots
      description: Attach any relevant logs or screenshots to help diagnose the issue.
      placeholder: "Drag and drop a screenshot or copy-paste log snippets here."

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Indicate the priority of this bug.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
